  
server:  port:  8080

spring:  application:    name: gateway#  cloud:#    gateway:#      discovery:#        locator:#          enabled: true#          lower-case-service-id: true
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    hostname: gateway
    prefer-ip-address: true


zuul:
  ignored-services: discovery, config, gateway, auth
  sensitiveHeaders:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
#  routes:
#    auth:
#      path: /auth/**
#      serviceId: auth
#      stripPrefix: true
#      sensitiveHeaders:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
