  
server:  port:  8080

spring:  application:    name: gateway
     
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    hostname: gateway
    prefer-ip-address: true

zuul:
  ignored-services: discovery, config, gateway, auth
  sensitiveHeaders:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
