spring: 
  application:
    name: micro-entity-b
  datasource:
    url: jdbc:mysql://localhost:3306/entities?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    generate-ddl: true
    hibernate:
      ddl-auto: update
security:
    oauth2:
      resource:
        tokenInfoUri: http://localhost:8090/oauth/check_token
      client:
        client-id: web
        client-secret: pass
server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    hostname: micro-entityB
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic