spring:
  application:
    name: micro-entity-b
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:file:~/entityB
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
    generate-ddl: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resource:        token-info-uri: http://localhost:8090/oauth/check_token
      client:
        client-id: web
        client-secret: pass 
server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    hostname: micro-entityB
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic