server:
  port: 8761  
spring:
  boot:
    admin:
      context-path: /admin
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    hostname: admin
    prefer-ip-address: true  

